connectmedica_blog:
    resource: "@ConnectmedicaBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@ConnectmedicaBlogBundle/Resources/config/routing.yml"
    type:     yaml
