 # app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            logout:
                path:   /admin/logout
                target: /
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check

        dev:
           pattern: ^/(_(profiler|wdt)|css|images|js)/
           security: false

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
